language: perl
sudo: false
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.10"
cache:
    directories:
        - local
before_install:
    - cpanm Carton
    - cpanm --test-only Crypt::Argon2
install:
    - carton install
script:
    - carton exec -- prove -lrv t
after_failure:
    - "cat ~/.cpanm/build.log"
